version: "3.6"
services:
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    networks:
      - backend
    links:
      - postgres:db
    expose:
      - 8080
  php:
    container_name: php
    build:
      context: "./docker/php/"
      args:
        PHP_VERSION: ${PHP_VERSION}
    networks:
      - backend
    volumes:
      - ./app/:/var/www/app/:ro
      - ./src/:/var/www/src/:ro
      - ./tests/:/var/www/tests/:ro
      - ./var/:/var/www/var/:z
      - ./vendor/:/var/www/vendor/:ro
      - ./web/:/var/www/html/:ro
    expose:
      - 9000
  apache:
    container_name: apache
    build:
      context: "./docker/apache/"
      args:
        APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - adminer
      - php
      - postgres
    networks:
      - frontend
      - backend
    ports:
      - "${HTTPS_PORT}:443"
    volumes:
      - ./web/:/var/www/html/:ro
  postgres:
    container_name: postgres
    image: postgres:${POSTGRES_VERSION:-latest}-alpine
    networks:
      - backend
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - 5432
networks:
  frontend: {}
  backend: {}
