database:
  hostname: localhost
  username: root
  dbname: mfgg
  password: ''
  prefix: tsms_
  driver: MySQLDatabaseDriver

# Old settings, remove them as needed

## Content settings
thumbnail_directory: '../tcsms/thumbnail'
file_directory: '../tcsms/file'
session_hotlink_protection: true

## Date settings
date_format: 'm/d/Y g:ia'
date_setting: 'since'

## Login settings
login_attempts_max: 10
login_attempts_wait: 300

## Registration Form Settings
username_min_length: 3
username_max_length: 32
password_min_length: 3
password_max_length: 72

## Resource settings
limit_per_page: 20

## Site settings
site_name: 'Mario Fan Games Galaxy'
site_abbr: 'MFGG'
